language: android
sudo: required
os: linux
dist: precise
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
notifications:
  email: false
android:
  components:
    - tools
    - tools
    - platform-tools
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - google-gdk-license-.+
script:
  - ./gradlew jar
  - ./update.sh
jdk:
  - oraclejdk8
